version: "3.8"
services:
  db:
    image: "postgres:13"
    ports:
      - "5435:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=storyMagic@123
      - POSTGRES_DB=storyMagic
